# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('password', models.CharField(max_length=6)),
                ('date', models.DateField(blank=True, default=b'2018-02-07', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=130)),
                ('password', models.CharField(max_length=6)),
                ('date', models.DateField(blank=True, default=b'2018-02-07', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Safe_file',
        ),
        migrations.DeleteModel(
            name='Safe_url',
        ),
    ]
