# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0002_auto_20180207_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfile',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerurl',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 15, 45, 45, 649659)),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 7, 15, 45, 45, 648882)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='password',
            field=models.CharField(max_length=10),
        ),
    ]
