# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0005_auto_20180207_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 12, 57, 31, 758561)),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='file',
            field=models.FileField(default='Doc/None/no-doc.pdf', upload_to='Doc/'),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 12, 57, 31, 757998)),
        ),
    ]
