# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0006_auto_20180208_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 23, 29, 426661))),
                ('url_activity', models.TextField()),
                ('file_activity', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 23, 29, 426018)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 23, 29, 425392)),
        ),
    ]
