# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 16:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0008_auto_20180208_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date',
            field=models.DateTimeField(default='2018-02-08'),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 48, 38, 715938)),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='password',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 16, 48, 38, 715386)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
