# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 17:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0009_auto_20180208_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archive',
            new_name='ActivityArchive',
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 11, 17, 708776)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 11, 17, 708203)),
        ),
    ]
