# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 17:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0010_auto_20180208_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarchive',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 16, 4, 357551)),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 16, 4, 356958)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 16, 4, 356327)),
        ),
    ]
