# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zad', '0011_auto_20180208_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityarchive',
            name='date',
            field=models.DateField(blank=True, default='2018-02-08', null=True),
        ),
        migrations.AlterField(
            model_name='customerfile',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 17, 24, 62785)),
        ),
        migrations.AlterField(
            model_name='customerurl',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 17, 17, 24, 62207)),
        ),
    ]
